# Generated by Django 4.1.7 on 2023-02-22 22:08

# django imports
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("store", "0001_initial")]

    operations = [
        migrations.RenameField(
            model_name="storehours", old_name="store_id", new_name="store"
        ),
        migrations.RenameField(
            model_name="storestatus", old_name="store_id", new_name="store"
        ),
    ]
